name: better_help
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_screenutil: ^0.7.0
  flutter_bloc: ^2.1.1
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.0.0-rc.1
  webview_flutter: ^0.3.18+1
  equatable: ^1.0.1
  firebase_auth: ^0.15.2
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.0+1
  firebase_messaging: ^6.0.9
  rxdart: ^0.22.6
  json_annotation: ^3.0.0
  google_sign_in: ^4.1.0
  uuid: ^2.0.4
  bubble: ^1.1.9+1
  flash: ^1.2.0
  get_it: ^3.0.3
  dartz: ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3
  build_runner:

flutter:
  uses-material-design: true


  assets:
    - assets/images/welcome.png
    - assets/images/help_someone_colors.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
